BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE products MODIFY (image_url VARCHAR2(4000))';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1441 THEN
      NULL;
    ELSE
      RAISE;
    END IF;
END;
/

COMMIT;
